table Fact_Sales
	lineageTag: dbf8d288-2ed3-4a25-bd37-1e1bdecd0da8

	measure 'Total Sales' = SUM(Fact_Sales[sales_amount])
		lineageTag: 5fd309f0-58dc-4879-85d7-8e8f95e62cb7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Month Sales' =
			
			CALCULATE(
			    [Total Sales],
			    DATEADD(Dim_Date[date], -1, MONTH))
		lineageTag: eab34d0a-dcd1-46ad-bb01-8c970a813f09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' =
			
			DIVIDE(
			    [Total Sales] - [Previous Month Sales],
			    [Previous Month Sales]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 341a3c60-9684-41f1-9f42-52c9f7c15759

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALL(Dim_Date[date]),
			        Dim_Date[date] <= MAX(Dim_Date[date])
			    )
			)
		lineageTag: ce628126-6d52-4aea-91d7-fd65d3739d8e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Product Rank' =
			
			RANKX(
			    ALL(Dim_Product[item]),
			    [Total Sales],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: 2d245945-1f88-4339-9fb3-3d6a2a26827b

	measure 'Average Sales per Transaction' =
			
			DIVIDE(
			    [Total Sales],
			    DISTINCTCOUNT(Fact_Sales[sale_id])
			)
		lineageTag: 8fe85985-05fa-408c-96d4-5f48d295df0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 555aa195-6741-4b34-b36e-cbd2a28f264a
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 77db948b-4fc8-457f-8a24-41f8b6a2abf2
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: b0e97f12-6717-47b6-a623-32e6129a07c7
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 709d8bef-daf0-4e28-aeed-d5666008f06c
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: d36cd6f5-72cb-43b6-add3-702cd76920ed
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 3a0ee001-3347-4cfd-9ccd-fb29edee1d4b
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 151d2456-81bd-4b93-8763-d34138d12ce4
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 9878dd85-5f53-4ab9-82d2-a4fd32a523c9
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: fdd7d640-d244-4419-96bc-da9b4a10c199
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Akhil\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

